### PR TITLE
Fix warning fetching crop data

### LINKED ISSUE #5: PHP notice on WXR import - Undefined index: full
Looks like this is probably related to the php notice below, seems to trigger for each image

screen shot 2018-11-13 at 17 35 55

### PR DESCRIPTION
**Pull request by roborourke**
Fixes #5

When retrieving crop data it was possible the passed in a size that didn't exist in the array returned from `get_image_sizes()`. This occurred any time `image_downsize` was called.

Also patches warnings when the image metadata failed to determine the original image width and size. Rare but seen on some sites we host, possibly related to image size.

### CODE REVIEW

File: inc/cropper/namespace.php [hunk 1]
```diff
@@ -180,6 +188,13 @@ function attachment_js( $response, $attachment ) {
 	$meta         = wp_get_attachment_metadata( $attachment->ID );
 	$backup_sizes = get_post_meta( $attachment->ID, '_wp_attachment_backup_sizes', true );
 
+	// Ensure width and height are set.
```
Comment (joehoyle) [inline inc/cropper/namespace.php]: IMO we should not do this, and we want a fail state. We don't want to be calling `getimagesize` as that causes a remote fetch from s3 for each image. If the image width / height isn't set, something is wrong, and I think it's ok to fail in those cases.

Comment (roborourke) [reply inc/cropper/namespace.php]: Yeah I was reading up on `getimagesize` performance after the fact. It's a rare occurrence but also it's not actually related to the problem at hand. Will remove.

Comment (roborourke) [reply inc/cropper/namespace.php]: @joehoyle changed my mind - updated to return early but logging an error that tells you what image ID has an issue.
